# Generated by Django 6.0.3 on 2026-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
